eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZome: http://localhost:8761/
      
  instance:
    hostname: localhost
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://payment-service/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://order-service/order/bookOrder     
